### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by rsmolkin** [muhasturk/gitim#10]
When I tried to run 
python -m gitim -u

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/<me>/www/gitim/gitim.py", line 12, in <module>
    from github import Github
ModuleNotFoundError: No module named 'github'

**Comment by rsmolkin** [comment]
A co-worker told me I had to do python setup.py install first, but now I get this error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rsmolkin/www/gitim/gitim.py", line 108, in <module>
    gitim.clone_main()
  File "/Users/rsmolkin/www/gitim/gitim.py", line 76, in clone_main
    user = g.get_user().login
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/AuthenticatedUser.py", line 226, in login
    self._completeIfNotSet(self._login)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/GithubObject.py", line 259, in _completeIfNotSet
    self._completeIfNeeded()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/GithubObject.py", line 263, in _completeIfNeeded
    self.__complete()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/GithubObject.py", line 268, in __complete
    self._url.value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/Requester.py", line 185, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/Requester.py", line 231, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/Requester.py", line 284, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyGithub-1.39-py3.6.egg/github/Requester.py", line 309, in __requestRaw
    requestHeaders
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

**Comment by muhasturk** [comment]
The error logs seems like SSL error. Please change your network connection and try again.
