### ISSUE TITLE
Unable to run following instructions

### ISSUE THREAD

**Issue by ghost** [muhasturk/gitim#6]
Looking at your readme... ran the following commands

```
git clone https://github.com/muhasturk/gitim
cd gitim
python -m gitim -u
```

and got the error:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rhodecode/downloads/gitim/gitim.py", line 12, in <module>
    from github import Github
ImportError: No module named github
```

Not sure if my python install install is broken - unable to "pip install github".

Would be very helpful if you were to update your readme with details.

PS: Is there a python version dependency? would 2.7 work?

Thanks

**Comment by pwnyprod** [comment]
run setup.py will help

**Comment by Alexsey** [comment]
It requires some arguments:
```
$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by pwnyprod** [comment]
Maybe you use wrong python version? (py2.7 vs py3.x)

**Comment by brucedeen** [comment]
```bash
python setup.py install
```

**Comment by muhasturk** [comment]
I have added installation guide to readme file. Thanks for contribution.
